# Generated by Django 3.1 on 2020-08-16 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_paciente', models.CharField(max_length=250, verbose_name='Nome do paciente')),
                ('data_nascimento', models.DateTimeField(verbose_name='Data de Nascimento')),
                ('sexo', models.SmallIntegerField(choices=[(1, 'Masculino'), (2, 'Feminino')], default=1, editable=False)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'paciente',
            },
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_ref', models.CharField(max_length=250, verbose_name='Refeição')),
            ],
            options={
                'db_table': 'refeicao',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=100, verbose_name='Receita')),
                ('descricao', models.TextField()),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_ref', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.refeicao', verbose_name='Tipo da Refeição')),
            ],
            options={
                'db_table': 'receita',
            },
        ),
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_presc', models.DateTimeField(verbose_name='Data da Prescrição')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=3)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('ref_paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.paciente', verbose_name='Paciente')),
                ('ref_receita', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.receita', verbose_name='Receita')),
            ],
            options={
                'db_table': 'prescricao',
            },
        ),
    ]
